models/Tasks.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tasks".
 *
 * @property integer $id
 * @property string $title
 * @property string $descr
 * @property string $dateTime
 *
 * @property VolunteerTask[] $volunteerTasks
 */
class Tasks extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tasks';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'descr'], 'required'],
            [['descr'], 'string','max' => 1000],
            [['title','filePath'], 'string', 'max' => 120],
            [['dateTime', 'dateCreate'], 'string', 'max' => 11],
            [['isActive'],'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заглавие',
            'descr' => 'Текст',
            'dateTime' => 'Дата',
            'dateCreate' => 'Дата создания',
            'filePath'=> 'Фото',
            'isActive'=>'Активно'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */

    public function getUserTask()
    {
        return $this->hasMany(UserTask::className(), ['taskId' => 'id']);
    }

    /** @inheritdoc */
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->setAttribute('dateCreate', time());
        }
        return parent::beforeSave($insert);
    }
}

controllers/TasksController.php
<?php

namespace app\controllers;

use app\models\AuthAssignment;
use app\models\Messages;
use app\models\Needies;
use app\models\UploadForm;
use app\models\UserTask;
use app\models\Volunteers;
use app\models\Angels;
use Yii;
use app\models\Tasks;
use app\models\TasksSeach;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use yii\data\Pagination;

/**
 * TasksController implements the CRUD actions for Tasks model.
 */
class TasksController extends Controller
{

    protected $userId;
    protected $volunteerId;
    protected $angelId;

    public function __construct($id, $module, $config = [])
    {
        $this->userId = Yii::$app->user->id;
        $this->volunteerId = Volunteers::find()->where(['userId' => $this->userId])->one()->id;
        $this->angelId = Angels::find()->where(['userId' => $this->userId])->one()->id;
        parent::__construct($id, $module, $config);
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {

            if(!Yii::$app->user->isGuest) {
                Yii::$app->DLL->onliner(Yii::$app->user->id);
            }

            $role = key(Yii::$app->authManager->getRolesByUser(Yii::$app->user->id));
            if ($action->id != 'list' && $action->id != 'more' && $action->id != 'apply') {
                if (!Yii::$app->user->can('adminIndex')) {
                    Yii::$app->session->setFlash('error', 'Доступ запрещен');
                    return $this->redirect('/site/index', []);
                } else {
                    $this->layout = 'admin';
                }
            } elseif ($role == 'admin') {
                return $this->redirect(['subscribe/index']);
            }
            return true;
        }
        return false;
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Lists all Tasks models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TasksSeach();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $isActive = [
            ['id'=>'0','name'=>'Не Активна'],
            ['id'=>'1','name'=>'Активна']
        ];
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'isActive' => $isActive,
        ]);
    }

    /**
     * Displays a single Tasks model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $userTasks = $model->userTask;
        $users= [];

        foreach ($userTasks as $userTask) {
            $role = Yii::$app->DLL->getRoleByUserId($userTask->userId);
            switch($role)
            {
                case 'angel': $users[] =  Angels::find()->where(['userId'=>$userTask->userId])->one(); $url []= 'angels/view'; break;
                case 'volunteer': $users[] = Volunteers::find()->where(['userId'=>$userTask->userId])->one(); $url []= 'volunteers/view'; break;
                case 'needy' : $users[] = Needies::find()->where(['userId'=>$userTask->userId])->one(); $url [] = 'needies/view'; break;
            }

        }
        switch($model->isActive){
            case 1: $isActive = 'Активная';break;
            case 0: $isActive = 'Не активная';break;
        }

        return $this->render('view', [
            'model' => $model,
            'users' => $users,
            'isActive' => $isActive,
            'url'=>$url
        ]);
    }

    /**
     * Creates a new Tasks model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Tasks();
        $upload = new UploadForm();
        $model->isActive = 1;
        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            $filePath = $upload->tasksFile();
            $model->filePath = $filePath;
            if(!empty($model->dateTime)){
                $model->dateTime = strtotime($model->dateTime);
            }
            $model->save(false);

            /** new task notifier */
            $messagesModel = new Messages();
            $messagesModel->taskNotification($model->title);

            /** уведомление в меню, о новом задании */
            $volunteersArray = AuthAssignment::find()->where(['item_name' => 'volunteer'])->all();
            foreach ($volunteersArray as $volunteer) {
                Yii::$app->DLL->addNotification($volunteer->user_id);
            }


            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'upload'=>$upload,
            ]);
        }
    }

    /**
     * Updates an existing Tasks model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->isActive = 1;
        $upload = new UploadForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->dateTime = strtotime($model->dateTime);
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            $filePath = $upload->tasksFile();
            if(!empty($filePath)) {
                $model->filePath = $filePath;
            }
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'upload'=>$upload,
            ]);
        }
    }

    /**
     * Deletes an existing Tasks model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Просмотр списка заданий
     * @return string
     */
    public function actionList()
    {
//        if (\Yii::$app->user->can('task')) {
            $query = Tasks::find()->where(' (dateTime >=' . time() . ' OR dateTime = "" ) AND isActive = 1');
            $countQuery = clone $query;
            $pages = new Pagination(['totalCount' => $countQuery->count(), 'defaultPageSize' => 9]);

            $models = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->orderBy(['id' => SORT_DESC])
                ->all();

            return $this->render('list', [
                'models' => $models,
                'pages' => $pages,
                'userId' => $this->userId,

            ]);
//        } else {
//            Yii::$app->session->setFlash('error', 'Доступ запрещен');
//            return $this->redirect('/site/index', []);
//        }
    }

    /**
     * Просмотр подбродной информации о задании
     * @param $id
     * @return string|\yii\web\Response
     */
    public function actionMore($id)
    {
//        if (\Yii::$app->user->can('task')) {
            $model = Tasks::find()->where(['id' => $id])->one();
            if ($model->isActive == 0) {
                return $this->redirect('list', []);
            }

            return $this->render('more', [
                'model' => Tasks::find()->where(['id' => $id])->one(),
                'userId' => $this->userId,
            ]);
//        } else {
//            Yii::$app->session->setFlash('error', 'Доступ запрещен');
//            return $this->redirect('/site/index', []);
//        }
    }

    /**
     * Подписка / отписка на задания
     * @param $id
     * @param $action
     * @return \yii\web\Response
     */
    public function actionApply($id, $action)
    {
        $userTaskModel = new UserTask();
        if (!empty($action)) {
            if ($action == 'subscribe') {
                $userTaskModel->setAttributes([
                    'userId' => $this->userId,
                    'taskId' => $id
                ]);
                $userTaskModel->save();
                Yii::$app->session->setFlash('message', 'Спасибо что откликнулись. Наш администратор свяжется с Вами в ближайшее время.');
            } elseif($action == 'unsubscribe') {
                $userTaskModel->deleteAll(['userId' => $this->userId, 'taskId' => $id ]);
                Yii::$app->session->setFlash('message', 'Вы больше не подписаны на выполнение задания.');
            }
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Finds the Tasks model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tasks the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tasks::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/tasks/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use vova07\imperavi\Widget;

/* @var $this yii\web\View */
/* @var $model app\models\Tasks */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tasks-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descr')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'plugins' => [
                'clips',
                'fullscreen'
            ]
        ]
    ]);
    ?>


    <div class="form-group field-tasks-datetime">
        <label class="control-label" for="tasks-datetime">Дата</label>
        <?php
        if(!empty( $model->dateTime)){
            $model->dateTime = Yii::$app->formatter->asDatetime($model->dateTime, "php:m/d/Y ");}
        ?>
        <?echo MaskedInput::widget([
            'model' => $model,
            'attribute' => 'dateTime',
            'name' => 'dateTime',
            'mask' => '99/99/9999',
        ]);
        ?>
        <div class="help-block"></div>
    </div>


    <?php $file = $model->filePath; ?>
    <?php if (!empty($file)): ?>
        <div class="form-active">
            <p><label class="control-label">Фото</label></p>

            <div class="image-user">
                <div class="icons">

                </div>
                <span class="photo">
                    <a class="profile-gallery-item"
                       href="<?= Yii::getAlias('@web') . '/images/tasks/' . $file ?>"
                       data-fancybox-group="gallery" title="">
                        <img
                            src="<?= Yii::getAlias('@web') . '/images/tasks/m_' . $file ?>"
                            alt="">
                    </a>
                </span>
            </div>
        </div>
    <?php else: ?>
        <p><label class="control-label">Аватар</label></p>
        <img src="<?= Yii::getAlias('@web') . '/images/no-image.jpeg' ?>">
    <?php endif; ?>
    <div class="clr"></div>

    <?= $form->field($upload, 'imageFile')->fileInput()->label(false) ?>

    <?= $form->field($model, 'isActive')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/tasks/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TasksSeach */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tasks-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'descr') ?>

    <?= $form->field($model, 'dateTime') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/tasks/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;
use vova07\imperavi\Widget;

/* @var $this yii\web\View */
/* @var $model app\models\Tasks */

$this->title = 'Создать Задание';
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content tasks-create">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-medkit"></i>

                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
                </div>
                <div class="box-body">
                    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

                    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

<!--                    --><?//= $form->field($model, 'descr')->textarea(['rows' => 6]) ?>
                    <?= $form->field($model, 'descr')->widget(Widget::className(), [
                        'settings' => [
                            'lang' => 'ru',
                            'minHeight' => 200,
                            'plugins' => [
                                'clips',
                                'fullscreen'
                            ]
                        ]
                    ]);
                    ?>

<!--                    --><?php //$model->dateTime = Yii::$app->formatter->asDatetime(time(), "php:m/d/Y ") ?>
                    <?= $form->field($model, 'dateTime')->widget(
                        DatePicker::className(), [
                        // inline too, not bad
                        'inline' => true,
                        // modify template for custom rendering
                        'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
                        'clientOptions' => [
                            'autoclose' => true,
                            'format' => 'mm/d/yyyy'
                        ]
                    ]); ?>


                    <?= $form->field($upload, 'imageFile')->fileInput()->label(false) ?>

                    <?= $form->field($model,'isActive')->checkbox()?>

                    <div class="form-group">
                        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>


                </div>
            </div>
        </div>
    </div>
</section>

views/tasks/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use dosamigos\datepicker\DatePicker;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TasksSeach */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Задания';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content static-pages-index">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-medkit"></i>

                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>

                    <div class="box-tools">
                        <?= Html::a('Создать задание', ['create'], ['class' => 'btn btn-success']) ?>
                    </div>
                </div>
                <div class="box-body">


                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [

                            [
                                'attribute' => 'id',
                                'filter' => false,
                            ],
                            'title',
                            [
                                'attribute' => 'descr',
                                'format' => 'ntext',
                                'value' => function ($data) {
                                    return Yii::$app->DLL->subStr($data->descr);
                                },
                                'options' => ['width' => '400'],
                            ],
                            [
                                'attribute' => 'dateTime',

                                'value' => function ($data) {
                                    if (!empty($data->dateTime)) {
                                        return Yii::$app->formatter->asDatetime($data->dateTime, "php:m/d/Y ");
                                    } else {
                                        return ' ';
                                    }
                                },
                                'filter' => DatePicker::widget([
                                    'model' => $searchModel,
                                    'attribute' => 'dateTime',
                                    'template' => '{addon}{input}',
                                    'clientOptions' => [
                                        'autoclose' => true,
                                        'format' => 'd/mm/yyyy'
                                    ]
                                ]),
                                'options' => ['width' => '300'],

                            ],
                            [
                                'attribute' => 'id',
                                'format' => 'raw',
                                'label'=> 'Волонтеры',
                                'value' => function ($data) {
                                    $count = count($data->userTask);
                                    if ($count > 0) {
                                        return '<span class="label bg-green "> ' . $count . '</span>';
                                    } else {
                                        return 'Нет';
                                    }
                                },
                                'filter' => false,

                            ],
                            [
                                'attribute' => 'isActive',
                                'format' => 'raw',
                                'label' => 'Активна',
                                'value' => function ($data) {
                                    switch ($data->isActive) {
                                        case 0:
                                            $isNew = 'Не активно';
                                            break;
                                        case 1:
                                            $isNew = ' <span class="label bg-green ">Активно</span>';
                                            break;
                                    }
                                    return $isNew;
                                },
                            ],



                            [
                                'class' => 'yii\grid\ActionColumn',
                                'options' => ['width' => '120'],
                                'template' => ' {comment} {view} {update}  {delete}',
                                'buttons' => [
                                    'comment' => function ($url, $model) {
                                        return Html::a('<span class="glyphicon glyphicon-comment"></span>', $url, [
                                            'title' => Yii::t('app', 'Комментарий'),
                                        ]);
                                    },

                                ],
                                'urlCreator' => function ($action, $model, $key, $index) {
                                    switch($action){

                                        case 'view':
                                            $url = Url::toRoute(['tasks/view','id'=>$model->id]);
                                            return $url;
                                        case 'update':
                                            $url = Url::toRoute(['tasks/update','id'=>$model->id]);
                                            return $url;
                                        case 'delete':
                                            $url = Url::toRoute(['tasks/delete','id'=>$model->id]);
                                            return $url;
                                        case 'comment':
                                            $url = Url::toRoute(['taskcomment/create','id'=> $model->id]);
                                            return $url;
                                    }
                                }
                            ],

                        ],
                    ]); ?>

                </div>
            </div>
        </div>
    </div>
</section>

views/tasks/list.php
<?php

use yii\widgets\Pjax;
use yii\bootstrap\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\LinkPager;

$this->title = 'DobroUA.com Задания для волонтеров';
$this->registerMetaTag(['name' => 'description', 'content' => Yii::$app->params['description']]);
$this->registerMetaTag(['name' => 'keywords', 'content' => Yii::$app->params['keywords']]);
?>


<div class="site-index">
    <!-- Tasks block -->
    <div class="container">
        <div class="page-header">
            <h1>Задания для волонтеров</h1>
        </div>
    </div>

    <div class="section">
        <div class="container task list">
            <?php if(!empty($models)):  ?>
                <?php foreach($models as $model): ?>

                    <div class="media">
                        <div class="media-left">
                            <a href="<?= Url::toRoute(['tasks/more', 'id' => $model->id]) ?>">
                                <?php if(!empty($model->filePath) && file_exists(Yii::getAlias('@app/web/images/tasks/' . $model->filePath))): ?>
                                    <img class="media-object img-rounded"
                                         src="<?= Yii::getAlias('@web/images/tasks/m2_' . $model->filePath) ?>"
                                         data-holder-rendered="true"
                                         style="width: 128px;">
                                <?php else: ?>
                                    <img class="media-object img-rounded"
                                         src="<?= Yii::getAlias('@web/images/no-image.jpeg') ?>" alt="avatar"
                                         data-holder-rendered="true"
                                         style="width: 128px; height: 128px;">
                                <?php endif; ?>
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading"><a href="<?= Url::toRoute(['tasks/more', 'id' => $model->id]) ?>"><?= $model->title ?></a></h4>

                            <?php if(!empty($model->dateTime)): ?>
                                <small><?= Yii::$app->formatter->asDatetime($model->dateTime, "php:d.m.Y") ?></small>
                            <?php endif; ?>

                            <p><?= Yii::$app->DLL->subStr($model->descr) ?></p>

                            <?php /** Если не заполнен профайл не могу подписаться на задания */ ?>
                            <?php $profile = Yii::$app->DLL->getProfile(); ?>
                            <?php if(!empty($profile)): ?>
                                <?php if(!in_array($userId, ArrayHelper::map($model->userTask, 'id', 'userId'))): ?>
                                    <?= Html::a("Могу помочь <span class='badge'>" . count($model->userTask) . "</span>", ['tasks/apply', 'id' => $model->id, 'action' => 'subscribe'], ['class' => 'btn btn-primary text-right']);?>
                                <?php else: ?>
                                    <?= Html::a("Не могу помочь<span class='badge'></span>", ['tasks/apply', 'id' => $model->id, 'action' => 'unsubscribe'], ['class' => 'btn btn-primary text-right']);?>
                                <?php endif; ?>
                            <?php endif; ?>

                        </div>
                    </div>
                <?php endforeach; ?>

                <div style="height: 50px"></div>
            <?php else: ?>
                <h3>Нет активных заданий</h3>
            <?php endif; ?>
        </div>
    </div>

    <!-- Pagination block -->
    <div class="container">
        <div class="row">
            <?= LinkPager::widget([
                'pagination' => $pages,
            ]);
            ?>
        </div>
    </div>
    <!-- /Pagination block -->

    <!-- /Tasks block -->
</div>

views/tasks/more.php
<?php

use yii\widgets\Pjax;
use yii\bootstrap\Html;
use yii\helpers\ArrayHelper;
use app\components\SubscribersWidget;
use \app\components\TaskCommentWidget;

$this->title = 'DobroUA.com Задание ' . $model->title;
$this->registerMetaTag(['name' => 'description', 'content' => Yii::$app->params['description']]);
$this->registerMetaTag(['name' => 'keywords', 'content' => Yii::$app->params['keywords']]);
?>


<div class="site-index">
    <div class="container">
        <div class="page-header">
            <h1><?= 'Задание ' . $model->title ?></h1>
        </div>
    </div>

    <!-- Tasks block -->
    <div class="container task more">
        <div class="row">
            <div class="col-xs-12 col-sm-4">
                <div id="gallery">
                <?php if(!empty($model->filePath) && file_exists(Yii::getAlias('@app/web/images/tasks/' . $model->filePath))): ?>
                    <a href="<?= Yii::getAlias('@web/images/tasks/m_' . $model->filePath) ?>">
                        <img src="<?= Yii::getAlias('@web/images/tasks/' . $model->filePath) ?>" alt="" >
                    </a>
                <?php else: ?>
                    <img src="<?= Yii::getAlias('@web/images/no-image.jpeg') ?>" alt="avatar" class="img-rounded">
                <?php endif; ?>
                    </div>
                <script type="text/javascript">(function (w, doc) {
                        if (!w.__utlWdgt) {
                            w.__utlWdgt = true;
                            var d = doc, s = d.createElement('script'), g = 'getElementsByTagName';
                            s.type = 'text/javascript';
                            s.charset = 'UTF-8';
                            s.async = true;
                            s.src = ('https:' == w.location.protocol ? 'https' : 'http') + '://w.uptolike.com/widgets/v1/uptolike.js';
                            var h = d[g]('body')[0];
                            h.appendChild(s);
                        }
                    })(window, document);
                </script>
                <div data-background-alpha="0.0" data-buttons-color="#FFFFFF"
                     data-counter-background-color="#ffffff" data-share-counter-size="12"
                     data-top-button="false" data-share-counter-type="separate" data-share-style="1"
                     data-mode="share" data-like-text-enable="false" data-mobile-view="false"
                     data-icon-color="#ffffff" data-orientation="horizontal" data-text-color="#000000"
                     data-share-shape="rectangle" data-sn-ids="fb.vk.ok." data-share-size="20"
                     data-background-color="#ffffff" data-preview-mobile="false"
                     data-mobile-sn-ids="fb.vk.tw.wh.ok.vb." data-pid="1486815"
                     data-counter-background-alpha="1.0" data-following-enable="false"
                     data-exclude-show-more="true" data-selection-enable="true"
                     class="uptolike-buttons"></div>
            </div>

            <div class="col-xs-12 col-sm-8">
                <p><?= $model->descr ?></p>
                <p>
                    <?php if(!empty($model->dateTime)): ?>
                        <span class="date">Дата события: <?= Yii::$app->formatter->asDatetime($model->dateTime, "php:d.m.Y") ?></span>
                    <?php endif; ?>


                    <?php /** Если не заполнен профайл не могу подписаться на задания */ ?>
                    <?php $profile = Yii::$app->DLL->getProfile(); ?>
                    <?php if(!empty($profile)): ?>
                        <?php if(!in_array($userId, ArrayHelper::map($model->userTask, 'id', 'userId'))): ?>
                            <?= Html::a("Могу помочь <span class='badge'>" . count($model->userTask) . "</span>", ['tasks/apply', 'id' => $model->id, 'action' => 'subscribe'], ['class' => 'btn btn-primary text-right' ,'style'=>'color:#fff']);?>
                        <?php else: ?>
                            <?= Html::a("Не могу помочь<span class='badge'></span>", ['tasks/apply', 'id' => $model->id, 'action' => 'unsubscribe'], ['class' => 'btn btn-primary text-right']);?>
                        <?php endif; ?>

                    <?php endif; ?>
                </p>
            </div>
        </div>
    </div>
    <?php if(!empty($profile)): ?>
    <?= TaskCommentWidget::widget(['taskId' => $model->id]); ?>
    <?php endif; ?>

    <?= SubscribersWidget::widget(['model' => $model->userTask]); ?>

</div>