models/Angels.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "angels".
 *
 * @property integer $id
 * @property integer $userId
 * @property string $name
 * @property string $lastname
 * @property integer $age
 * @property integer $cityId
 * @property string $phone
 * @property string $email
 * @property string $vk
 * @property string $fb
 * @property integer $avatarId
 * @property integer $statusId
 * @property integer $isPlus
 *
 * @property Users $user
 * @property Cities $city
 * @property Statuses $status
 */
class Angels extends \yii\db\ActiveRecord
{
    public $type = 2;
    public $ratingOrder;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'angels';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['userId', 'name', 'lastname', 'age', 'cityId','mainCountryId', 'email', 'showPhone', 'showEmail', 'avatarId', 'statusId', 'isPlus'], 'required'],
            [['userId', 'age', 'cityId', 'mainCountryId', 'avatarId', 'showPhone', 'statusId', 'isPlus'], 'integer'],
            [['email'], 'email'],
            [['age'], 'integer', 'max' => 99],
            [['city', 'phone', 'email', 'vk', 'fb','time'], 'string', 'max' => 120],
            [['name','lastname'],'string','max'=>20],
            [['createTime','help'],'string','max'=>255],
            [['type'],'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userId' => 'User ID',
            'name' => 'Имя',
            'lastname' => 'Фамилия',
            'age' => 'Возраст',
            'city' => 'Город',
            'cityId' => 'Город',
            'phone' => 'Телефон',
            'email' => 'Email',
            'showPhone' => 'Показывать телефон',
            'showEmail' => 'Показывать  email',
            'vk' => 'Ссылка на страницу в VK',
            'fb' => 'Ссылка на страницу в FB',
            'avatarId' => 'Ваше фото',
            'statusId' => 'Статус',
            'isPlus' => 'Элитный',
            'time' => 'Укажите удобное время для звонка',
            'mainCountryId'=>'Страна',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'userId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCities()
    {
        return $this->hasOne(Cities::className(), ['id' => 'cityId']);
    }

    public function getCityTitle()
    {
        return $this->cities->title;
    }

    public function getCountry()
    {
        return $this->hasOne(Countries::className(), ['mainId' => 'mainCountryId']);
    }

    public function getCountryTitle()
    {
        return $this->country->title;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Statuses::className(), ['id' => 'statusId']);
    }

    /**
     *
     */
    public function getRating()
    {
        return $this->hasOne(Ratings::className(), ['userId' => 'userId']);
    }

    /**
     * @return mixed
     */
    public function getRatingCount() {
        return $this->hasMany(Ratings::className(), ['userId' => 'userId'])
            ->sum('rating');
    }

    /**
     * @return array|\yii\db\ActiveRecord[]
     */
    public function getNewAngels()
    {
        $a = time()-86400;

        return $this->find()
            ->where('createTime > ' .$a)
            ->asArray()
            ->all();
    }

    /**
     * @return array|\yii\db\ActiveRecord[]
     */
    public function getReversedAngels()
    {
        return $this->find()
            ->where(['statusId' => 4])
            ->asArray()
            ->all();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAvatar()
    {
        return $this->hasOne(Files::className(), ['id' => 'avatarId']);
    }

    /**
     *
     */
    public function getFile()
    {
        return $this->hasOne(Files::className(), ['id' => 'avatarId']);
    }

    /** @inheritdoc */
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->setAttribute('vk', Yii::$app->DLL->getLinkId($this->vk));
            $this->setAttribute('fb', Yii::$app->DLL->getLinkId($this->fb));
        }
        return parent::beforeSave($insert);
    }

    /** @inheritdoc */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        if ($insert) {
            $role = key(Yii::$app->authManager->getRolesByUser($this->userId));
            if (empty($role)) {
                $auth = Yii::$app->authManager;
                $authorRole = $auth->getRole('angel');
                $auth->assign($authorRole, $this->userId);
            }
        }
    }
}

controllers/AngelsController.php
<?php

namespace app\controllers;

use app\models\Cities;
use app\models\Comments;
use app\models\Countries;
use app\models\Files;
use app\models\Statuses;
use app\models\UploadForm;
use app\models\UserHelp;
use app\models\Users;
use Yii;
use app\models\Angels;
use app\models\AngelsSeach;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\data\Pagination;
use yii\imagine\Image;
use yii\web\UploadedFile;

/**
 * AngelsController implements the CRUD actions for Angels model.
 */
class AngelsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if(!Yii::$app->user->isGuest) {
                Yii::$app->DLL->onliner(Yii::$app->user->id);
            }
          $role = key(Yii::$app->authManager->getRolesByUser(Yii::$app->user->id));
          if ($action->id != 'list' && $action->id != 'more') {
              if (!Yii::$app->user->can('adminIndex')) {
                  Yii::$app->session->setFlash('error', 'Доступ запрещен');
                  return $this->redirect('/site/index', 302);
              } else {
                  $this->layout = 'admin';
              }
          } elseif ($role == 'admin') {
              return $this->redirect(['subscribe/index']);
          }
          return true;
        }
        return false;
    }

    /**
     * Lists all Angels models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AngelsSeach();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Angels model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $filesModel = new Files();
        $model = $this->findModel($id);
        $images = $filesModel->getFileType($model->userId, 1);
        return $this->render('view', [
            'model' => $model,
            'images' => $images,
        ]);
    }

    /**
     * Creates a new Angels model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Angels();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'cities' => ArrayHelper::map(Cities::find()->asArray()->all(), 'id', 'title'),
                'statuses' => ArrayHelper::map(Statuses::find()->all(), 'id', 'title')
            ]);
        }
    }

    /**
     * Updates an existing Angels model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $filesModel = new Files();
        $model = $this->findModel($id);
        $upload = new UploadForm();
        $upload->scenario = 'avatarUpload';

        $images = $filesModel->getFileType($model->userId, 1);
        if ($model->load(Yii::$app->request->post()) ) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            if (!empty($upload->imageFile)) {
                $model->avatarId = $upload->upload($model->userId);
            }
            $model->fb = Yii::$app->DLL->getLinkId($model->fb);
            $model->vk = Yii::$app->DLL->getLinkId($model->vk);
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'countries' => ArrayHelper::map(Countries::find()->orderBy(['order' => SORT_ASC])->all(), 'mainId', 'title'),
                'cities' => ArrayHelper::map(Cities::find()->where(['countryId' => 2])->orderBy(['title' => SORT_ASC])->asArray()->all(), 'id', 'title'),
                'statuses' => ArrayHelper::map(Statuses::find()->all(), 'id', 'title'),
                'images' => $images,
                'upload'=>$upload,
            ]);
        }
    }

    /**
     * Deletes an existing Angels model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = new Users();
        $userArr = $this->findModel($id);
        $user = $model->findOne(['id'=>$userArr->userId]);
        $user->delete();
        return $this->redirect(['index']);
    }

    /**
     * @return string
     */
    public function actionList()
    {

        $angels = new ActiveDataProvider([
            'query' => Angels::find()->where(['statusId' => 2])->orderBy(['rating' => SORT_DESC, 'id' => SORT_DESC]),
            'pagination' => [
                'pageSize' => 8,
            ],
        ]);
        return $this->render('list', [
                'angels' =>$angels
        ]);
    }


    /**
     * @return string
     */
    public function actionMore($id)
    {
        $model = $this->findModel($id);
        $helps = new ActiveDataProvider([
            'query' => UserHelp::find()->where(['fromUserId' => $model->userId, 'isVerify' => 1])->orderBy(['dateTime' => SORT_DESC]),
            'pagination' => [
                'pageSize' => 4,
            ],
        ]);
        return $this->render('more', [
            'model' => $model,
            'helps' => $helps,
        ]);
    }

    /**
     *
     */
    public function actionAddWallComment()
    {
        $model = new Comments();
        $comment = Yii::$app->request->post('Comments');
        if (!empty($comment)) {
            $model->attributes = $comment;
            if ($model->save(false)) {
                Yii::$app->session->setFlash('wallMessage', 'Спасибо за ваш отзыв. Ваш отзыв появится на сайте после подтверждения администратором');
            }
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

    /**
     * Finds the Angels model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Angels the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Angels::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     *
     */
    public function actionDelavatar()
    {
        $filesModel = new Files();
        $avatarId = Yii::$app->request->post('avatarId');
        $delete = $filesModel->findOne(['id' => $avatarId]);
        $delete->delete();
    }

    /**
     * @param $id
     * @return \yii\web\Response
     */
    public function actionApproved($id)
    {
        $angelsModel = new Angels();
        $angel = $angelsModel->findOne(['id'=>$id]);
        $angel->statusId = 2;
        $angel->save(false);
        return $this->redirect(['index']);
    }

    public function actionRotateImg()
    {
        $id = Yii::$app->request->post('id');
        $side = Yii::$app->request->post('side');
        if ($id !== null || $side !== null) {
            $imagine = Image::getImagine();
            $file = Files::findOne($id);
            $path = realpath(Yii::getAlias('@app') . '/web/images/' . $file->userId . '/' . $file->path);
            $pathM = realpath(Yii::getAlias('@app') . '/web/images/' . $file->userId . '/m_' . $file->path);
            $image = $imagine->open($path);
            $imageM = $imagine->open($pathM);
            $angle = null;
            if ($side == 'left') {
                $angle = -90;
            } else {
                $angle = 90;
            }
            $image->rotate($angle)->save($path);
            $imageM->rotate($angle)->save($pathM);
        }
    }

    public function actionComment($id)
    {
        $user = new Angels();
        $model = new Comments();
        $statusModel = new Statuses();
        $status = $statusModel->getAllStatuses();
        $angels = $user->find()->where(['id'=>$id])->one();

        if ($model->load(Yii::$app->request->post())) {

            $model->save();

            return $this->redirect(['index']);
        }
        return $this->render('comment',[
            'model'=>$model,
            'angels'=>$angels,
            'status'=>$status,
        ]);
    }

}

views/angels/_info.php
<h3><?= $model->name . ' ' . $model->lastname ?></h3>
<span class="city"><?= $model->countryTitle . ', ' . $model->city ?></span> <br>


<p><b>Возраст: </b> <?= $model->age ?> <?= Yii::$app->DLL->getWordEnd('', 'лет', 'год', 'года', 'лет', $model->age) ?>

<?php if(!empty($model->phone) && $model->showPhone == 0): ?>
    <p><b>Телефон: </b><?= $model->phone ?></p>
<?php endif ?>

<?php if(!empty($model->email) && $model->showEmail == 0): ?>
    <p><b>Email: </b><?= $model->email ?></p>
<?php endif ?>

<?php if(!empty($model->help)): ?>
    <p><b>Могу помочь: </b><?= $model->help ?></p>
<?php endif ?>

<?php if(!empty($model->vk)): ?>
    <a target="_blank" href="https://www.vk.com/<?= $model->vk ?>"><i class="fa social fa-vk"></i></a>
<?php endif; ?>

<?php if(!empty($model->fb)): ?>
    <a target="_blank" href="https://facebook.com/<?= $model->fb ?>"><i class="fa social fa-facebook-official"></i></a>
<?php endif; ?>

views/angels/_view_list.php
<?php

use yii\helpers\Url;
$this->title = 'Ангелы проекта - Мир добрых людей';
$this->registerMetaTag(['name' => 'description', 'content' => 'На этой страничке вы можете познакомиться и получить информацию про ангелов проекта, оказать помощь и стать ангелом']);
?>

<div class="col-md-6 col-sm-6 col-xs-12 b_persons">
    <div class="b_persons_item">
        <div class="b_pic"><a href="<?= Url::toRoute(['more', 'id' => $model->id]) ?>">
                <?php if(!empty($model->file->path) && file_exists(Yii::getAlias('@app/web/images/' . $model->userId . '/m_' . $model->file->path))): ?>
                    <img src="<?= Yii::getAlias('@web') . '/images/' . $model->userId . '/m_' . $model->file->path ?>" style="width: 106px" ></a></div>
                <?php else: ?>
                    <img src="<?= Yii::getAlias('@web') . '/images/no-image-man.png' ?>" style="width: 106px"></a></div>
                <?php endif; ?>
<!--                <img src="gfx/pic1.jpg"></a></div>-->
        <div class="b_desc_content" style="height: 116px;">
            <div class="b_title"><a href="<?= Url::toRoute(['more', 'id' => $model->id]) ?>"><?= $model->name . ' ' . $model->lastname ?></a><span class="b_locate"><?= $model->age . ' ' . Yii::$app->DLL->getWordEnd('', 'лет', 'год', 'года', 'лет', $model->age) . ' ' . $model->countryTitle . ', ' . $model->city ?></span>
            </div>
            <div class="b_desc"><span class="b_rating"><?= !empty($model->rating) ? 'Рейтинг: ' . $model->rating : ' ' ?></span></div>
        </div>
    </div>
</div>

views/angels/create.php
<?php

use yii\helpers\Html;

$this->title = 'Create Angels';
?>

<section class="content angels-create">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
                </div>
                <div class="box-body">
                    <?= $this->render('_form', [
                        'model' => $model,
                        'cities' => $cities,
                        'statuses' => $statuses
                    ]) ?>
                </div>
            </div>
        </div>
    </div>
</section>

views/angels/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\models\Statuses;
use yii\helpers\Url;

$this->title = 'Ангелы';
?>

<section class="content angels-index">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>

                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>

                    <div class="box-tools">

                    </div>
                </div>
                <div class="box-body">
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            [
                                'attribute' => 'id',
                                'value' => 'id',
                                'filter' => false
                            ],
                            'name',
                            'lastname',
                            'age',
                            [
                                'attribute'=>'mainCountryId',
                                'value'=>'countryTitle',
                                'filter'=>ArrayHelper::map(\app\models\Countries::find()->orderBy(['order' => SORT_ASC])->all(), 'mainId', 'title'),
                            ],
                            [
                                'attribute'=>'city',
                                'value'=>'city',
                            ],
                            'email:email',
                            'phone',
                            [
                                'attribute' => 'statusPosition',
                                'format' => 'raw',
                                'value' => function ($data) {
                                    $status = $data->status->title;
                                    switch ($status) {
                                        case 'новый':
                                            return '<span class="label bg-green "> ' . $data->status->title . '</span>';
                                            break;
                                        case 'измененный':
                                            return '<span class="label bg-blue "> ' . $data->status->title . '</span>';
                                            break;
                                        case 'отклоненный':
                                            return '<span class="label bg-yellow "> ' . $data->status->title . '</span>';
                                            break;
                                        default:
                                            return $data->status->title;
                                            break;
                                    }
                                },
                                'label' => 'Статус',
                                'filter' => ArrayHelper::map(Statuses::find()->select(['id', 'title'])->all(), 'id', 'title'),
                            ],

                            [
                                'attribute' => 'createTime',
                                'format' => 'raw',
                                'label' => 'Пользователь',
                                'filter' => false,
                                'value' => function($data)
                                {
                                    $time = time()-86400;
                                    if($data->createTime > $time){
                                        return '<span class="label bg-green "> ' . новый . '</span>';
                                    }else{
                                        return 'просмотреный';
                                    }
                                }
                            ],

                            [
                                'class' => 'yii\grid\ActionColumn',
                                'options' => ['width' => '120'],
                                'template' => '{message} {comment} {view} {update}  {delete}',
                                'buttons' => [
                                    'message' => function ($url, $model) {
                                        return Html::a('<span class="glyphicon glyphicon-envelope"></span>', $url, [
                                            'title' => Yii::t('app', 'Сообщение'),
                                        ]);
                                    },
                                    'comment' => function ($url, $model) {
                                        return Html::a('<span class="glyphicon glyphicon-comment"></span>', $url, [
                                            'title' => Yii::t('app', 'Комментарий'),
                                        ]);
                                    },


                                ],
                                'urlCreator' => function ($action, $model, $key, $index) {
                                    switch ($action) {
                                        case 'message':
                                            $url = Url::toRoute(['admin/messages','type'=>'2','id'=>$model->userId]);
                                            return $url;
                                        case 'view':
                                            $url = Url::toRoute(['angels/view','id'=>$model->id]);
                                            return $url;
                                        case 'update':
                                            $url = Url::toRoute(['angels/update','id'=>$model->id]);
                                            return $url;
                                        case 'delete':
                                            $url = Url::toRoute(['angels/delete','id'=>  $model->id]);
                                            return $url;
                                        case 'comment':
                                            $url = Url::toRoute(['angels/comment','id'=> $model->id]);
                                            return $url;
                                    }


                                }
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</section>

views/angels/more.php
<?php

use app\components\WallWidget;
use app\components\RatingPopupWidget;
use app\components\HelpToHistoryWidget;

$this->title =  $model->name . ' ' . $model->lastname .' - ангел благотворительной организации Мир добрых людей';
$this->registerMetaTag(['name' => 'description', 'content' =>'Ангел '.$model->name . ' ' . $model->lastname .' принимает активное участие в помощи детям и взрослым и вносит весомый вклад в наш проект']);
$this->registerMetaTag(['name' => 'keywords', 'content' => Yii::$app->params['keywords']]);
?>


    <div class="container b_fixed">
        <div class="b_left-side b_left_side_qustionare col-md-4 col-sm-4 col-xs-12">
            <div class="b_left_slider_person">
                <div class="slider-pro" id="b_person-slider">
                    <div class="sp-slides">
                        <!-- Slide 1 -->
                        <div class="sp-slide">
                            <?php if (!empty($model->file->path) && file_exists(Yii::getAlias('@app/web/images/' . $model->userId . '/' . $model->file->path))): ?>
                                <img style="width:280px;" class="sp-image"
                                     src="<?= Yii::getAlias('@web') . '/images/' . $model->userId . '/m_' . $model->file->path ?>"/>

                            <?php else: ?>
                                <img style="width:280px;" class="sp-image"
                                     src="<?= Yii::getAlias('@web') . '/images/noavatar.png' ?>"/>

                            <?php endif; ?>

                        </div>

                    </div>
                </div>

            </div>
            <center>
                <button type="button"
                        style="color: #fff; background: #006cff;border-radius: 20px;border-color: #006cff;box-shadow: none;"
                        class="btn btn-success" data-toggle="modal" data-target="#ratingModal">
                    Рейтинг <?= $model->ratingCount ?></button>
            </center>
        </div>

        <div class="b_person_desc col-md-8 col-sm-8 col-xs-12 pull-right">
            <div class="b_name"><h1><?= $model->name . ' ' . $model->lastname ?></h1><span
                    class="b_locate"><?= $model->age ?> <?= Yii::$app->DLL->getWordEnd('', 'лет', 'год', 'года', 'лет', $model->age) . ' ' . $model->countryTitle . ', ' . $model->city ?></span>
            </div>
            <p><b>Возраст:</b>
                <?= $model->age ?> <?= Yii::$app->DLL->getWordEnd('', 'лет', 'год', 'года', 'лет', $model->age) ?></p>
            <?php if (!empty($model->email) && $model->showEmail == 0): ?>
                <p><b>Email :</b> <?= $model->email ?></p>
            <?php endif ?>

            <?php if (!empty($model->phone) && $model->showPhone == 0): ?>
                <p><b>Телефон: </b><?= $model->phone ?></p>
            <?php endif ?>
            <?php if (!empty($model->help)): ?>
                <p><b>Могу помочь: </b><?= $model->help ?></p>
            <?php endif ?>
            <?php if (!empty($model->vk)): ?>
                <a target="_blank" href="https://www.vk.com/<?= $model->vk ?>"><i class="fa social fa-vk"></i></a>
            <?php endif; ?>
            <?php if (!empty($model->fb)): ?>
                <a target="_blank" href="https://facebook.com/<?= $model->fb ?>"><i
                        class="fa social fa-facebook-official"></i></a>
            <?php endif; ?>
            <?= WallWidget::widget(['userId' => $model->userId]); ?>
        </div>
        <div class="b_left-side b_left_side_qustionare col-md-4 col-sm-4 col-xs-12">

            <div class="b_helpers">
                <h2>Уже помог</h2>
                <div class="b_helpers_wrapper">
                    <div class="b_persons_list">
                        <?= \yii\widgets\ListView::widget([
                            'dataProvider' => $helps,
                            'itemView' => '_view_more',
                            'layout' => "{summary}\n{items}<div class=\"clear\"></div>{pager}",
                            'emptyText' => 'Список пуст',
                            'itemOptions' => [
                                'tag' => 'div',
                                'class' => 'b_persons_item',
                            ],
                        ]) ?>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <!--    <div class="section wall more helper angel">-->
    <!--        <div class="container">-->
    <!--            <div class="row">-->
    <!--              -->
    <!--                <div class="col-xs-12 col-sm-4 online">-->
    <!--                    <div class="row">-->
    <!--                        <div class="img">-->
    <!--                            <center>-->
    <!--                                --><?php //if (!empty($model->file->path) && file_exists(Yii::getAlias('@app/web/images/' . $model->userId . '/' . $model->file->path))): ?>
    <!--                                    <img-->
    <!--                                        src="--><? //= Yii::getAlias('@web') . '/images/' . $model->userId . '/m_' . $model->file->path ?><!--"-->
    <!--                                        alt="avatar" class="img-rounded img-responsive img-centered">-->
    <!--                                --><?php //else: ?>
    <!--                                    <img src="--><? //= Yii::getAlias('@web') . '/images/noavatar.png' ?><!--" alt="avatar"-->
    <!--                                         class="img-rounded img-responsive img-centered">-->
    <!--                                --><?php //endif; ?>
    <!--                            </center>-->
    <!---->
    <!--                        </div>-->
    <!--                    </div>-->
    <!--                    --><?php //$online = Yii::$app->DLL->getOnline($model->userId);
//                    if ($online == 1):
//                        ?>
    <!--                        <span class="label label-success label-online">Online</span>-->
    <!--                    --><?php //endif; ?>
    <!--                    <div class="row btns">-->
    <!--                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#ratingModal">-->
    <!--                            Рейтинг --><? //= $model->ratingCount ?><!--</button>-->
    <!--                    </div>-->
    <!--                </div>-->
    <!--          -->
    <!--                <div class="col-xs-12 col-sm-8">-->
    <!--                    <div class="info">-->
    <!--                        --><? //= $this->render('_info', [
//                            'model' => $model
//                        ]) ?>
    <!--                    </div>-->
    <!---->
    <!--                    <div class="info">-->
    <!--                        --><? //= HelpToHistoryWidget::widget(['userId' => $model->userId]); ?>
    <!--                    </div>-->
    <!--                </div>-->
    <!--              -->
    <!--            </div>-->
    <!--        </div>-->
    <!---->
    <!--        -->
    <!--        -->
    <!---->
    <!--    </div>-->


<?= RatingPopupWidget::widget(['userId' => $model->userId]); ?>