models/Shop.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "shop".
 *
 * @property integer $id
 * @property integer $size
 * @property string $color
 * @property string $consist
 * @property integer $cost
 * @property integer $avatarId
 */
class Shop extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'shop';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['size', 'color', 'consist', 'cost', 'avatarId'], 'required'],
            [[ 'avatarId'], 'integer'],
            [['color', 'cost','consist'], 'string', 'max' => 255],
            [['size','number','state'], 'string', 'max' => 45],
            [['text'],'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'size' => 'Размер',
            'color' => 'Цвет',
            'consist' => 'Состав',
            'cost' => 'Цена',
            'avatarId' => 'Фото',


            'number' => 'Номер',
            'state' => 'Состояние',
            'text' => 'Описание',
        ];
    }

    public function getAvatar()
    {
        return $this->hasOne(ShopPhoto::className(), ['id' => 'avatarId']);
    }
}

controllers/ShopController.php
<?php

namespace app\controllers;

use app\models\Needies;
use app\models\NeediesSeach;
use app\models\ShopPhoto;
use app\models\UploadForm;
use Yii;
use app\models\Shop;
use app\models\ShopSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\imagine\Image;
use Imagine\Image\ManipulatorInterface;

/**
 * AdminShopController implements the CRUD actions for Shop model.
 */
class ShopController extends Controller
{

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {

            if (!Yii::$app->user->isGuest || Yii::$app->DLL->getRoleByUserId(Yii::$app->user->id) !== 'moder') {
            } else {
                $this->layout = 'shop_admin';
            }
            return true;
        }
        return false;
    }

    public function behaviors()
    {
        return [

            'access' => [
                'class' => AccessControl::className(),
                'rules' => [

                    [
                        'allow' => true,
                        'actions' => ['shop', 'dress'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['shop', 'dress'],
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'view', 'watermark','counter','change'],
                        'allow' => true,
                        'roles' => ['moder'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Shop models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = 'shop_admin';
        $searchModel = new ShopSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionWatermark($id)
    {
        $file = ShopPhoto::findOne($id);
        $path = Yii::$app->basePath . '/web/images/shop/' . $file->shopId . '/big/' . $file->path;
        $pathM = Yii::$app->basePath . '/web/images/shop/' . $file->shopId . '/small/' . $file->path;
        \Yii::$app->DLL->watermark($path, 'images/sale.png');
        Image::thumbnail($path, 200, 200, ManipulatorInterface::THUMBNAIL_INSET)
            ->save($pathM);

        $this->redirect(['index']);
    }

    /**
     * Displays a single Shop model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $this->layout = 'shop_admin';
        $model = $this->findModel($id);
        $model->avatarId = Yii::getAlias('@web/images/shop/') . $id . '/small/' . $model->avatar->path;
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Shop model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = 'shop_admin';
        $model = new Shop();
        $upload = new UploadForm();
        $uploadFile = new UploadForm();
        $upload->scenario = 'shopAvatar';

        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            $model->save(false);
            $upload->shopAvatar($model->id);
            $uploadFile->file = UploadedFile::getInstances($upload, 'file');

            if (!empty($uploadFile->file)) {

                $uploadFile->shopPhotos($model->id);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'upload' => $upload,
                'uploadFile' => $uploadFile
            ]);
        }
    }

    /**
     * Updates an existing Shop model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $this->layout = 'shop_admin';
        $model = $this->findModel($id);
        $upload = new UploadForm();
        $uploadFile = new UploadForm();
        $upload->scenario = 'shopAvatar';
        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');

            $model->save(false);
            $upload->shopAvatar($model->id);
            $upload->file = UploadedFile::getInstances($upload, 'file');
            if (!empty($upload->file)) {

                $upload->shopPhotos($model->id);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'upload' => $upload,
                'uploadFile' => $uploadFile,
            ]);
        }
    }

    /**
     * Deletes an existing Shop model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->layout = 'shop_admin';
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Shop model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Shop the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Shop::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

//
    public function actionShop()
    {
        $searchModel = new ShopSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $needies = Needies::find()->where(['id' => 106])->one();

        return $this->render('dress', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'needies' => $needies,
        ]);
    }

    public function actionDress()
    {


        $id = $_GET['dressId'];
        $model = Shop::findOne($id);
        $files = ShopPhoto::find()->where(['shopId' => $id])->all();
        return $this->renderPartial('_view', [
            'model' => $model,
            'files' => $files,

        ]);
    }

    public function actionCounter()
    {
        $this->layout = 'shop_admin';
        $searchModel = new NeediesSeach();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,464);

        return $this->render('counter', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function  actionChange($id)
    {

        $this->layout = 'shop_admin';
        $model = Needies::findOne($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->save(false);

            return $this->redirect(['counter']);
        }
        return $this->render('change', [
            'model'=>$model,
        ]);
    }
}

views/shop/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Shop */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="shop-form">

    <?php $form = ActiveForm::begin([
        'id' =>'shop',
        'enableClientValidation' => true,
        'options' => ['enctype' => 'multipart/form-data'],
    ]); ?>

    <?= $form->field($model, 'size')->textInput() ?>

    <?= $form->field($model, 'color')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'consist')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cost')->textInput() ?>

    <?= $form->field($model, 'number')->textInput() ?>

    <?= $form->field($model, 'state')->textInput() ?>

    <?= $form->field($model, 'text')->textInput() ?>


    <label class="control-label" for="uploadform-file">Главное фото</label>
    <?= $form->field($upload, 'imageFile')->fileInput()->label(false) ?>
    <label class="control-label" for="uploadform-file">Дополнительные фото</label>
    <?= $form->field($uploadFile, 'file[]')->fileInput(['multiple' => true])->label(false) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/shop/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ShopSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="shop-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'size') ?>

    <?= $form->field($model, 'color') ?>

    <?= $form->field($model, 'consist') ?>

    <?= $form->field($model, 'cost') ?>

    <?php // echo $form->field($model, 'avatarId') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/shop/_view.php
<?php
$this->title = 'DobroUA.com Добрые платья ';

?>

<div class="container-fluid">
    <center><h3>Если Вам понравилось платье и Вы хотите его приобрести или примерять - обращайтесь по телефону <b>+380730763097 - Дария.</b></h3></center>
    <div class="col-md-6 dress-main">
        <img class="my-foto-container"
             src="<?= Yii::getAlias('@web/images/shop/') . $model->id . '/big/' . $model->avatar->path; ?>"
             data-large="<?= Yii::getAlias('@web/images/shop/'). $model->id .'/'.$model->avatar->path; ?>"
             title="Фото">
        <script type="text/javascript">(function (w, doc) {
                if (!w.__utlWdgt) {
                    w.__utlWdgt = true;
                    var d = doc, s = d.createElement('script'), g = 'getElementsByTagName';
                    s.type = 'text/javascript';
                    s.charset = 'UTF-8';
                    s.async = true;
                    s.src = ('https:' == w.location.protocol ? 'https' : 'http') + '://w.uptolike.com/widgets/v1/uptolike.js';
                    var h = d[g]('body')[0];
                    h.appendChild(s);
                }
            })(window, document);
        </script>
        <div data-background-alpha="0.0" data-buttons-color="#FFFFFF"
             data-counter-background-color="#ffffff" data-share-counter-size="12"
             data-top-button="false" data-share-counter-type="separate" data-share-style="1"
             data-mode="share" data-like-text-enable="false" data-mobile-view="false"
             data-icon-color="#ffffff" data-orientation="horizontal" data-text-color="#000000"
             data-share-shape="rectangle" data-sn-ids="fb.vk.ok." data-share-size="20"
             data-background-color="#ffffff" data-preview-mobile="false"
             data-mobile-sn-ids="fb.vk.tw.wh.ok.vb." data-pid="1486815"
             data-counter-background-alpha="1.0" data-following-enable="false"
             data-exclude-show-more="true" data-selection-enable="true"
             class="uptolike-buttons"></div>

    </div>

    <div class="col-md-6">
        <?php if(!empty($model->cost)):?>
        <h2><b> Цена :<?= $model->cost ?></b></h2>
        <?php endif;?>
        <?php if(!empty($model->color)):?>
        <h2><b> Цвет :<?= $model->color ?></b></h2>
        <?php endif;?>
        <?php if(!empty($model->consist)):?>
        <h2><b> Cостав :<?= $model->consist ?></b></h2>
        <?php endif;?>
        <?php if(!empty($model->size)):?>
        <h2><b> Размер :<?= $model->size ?></b></h2>
        <?php endif;?>
        <?php if(!empty($model->state)):?>
            <h2><b> Состояние:<?= $model->state ?></b></h2>
        <?php endif;?>
        <?php if(!empty($model->text)):?>
            <h2><b> Описание:<?= $model->text ?></b></h2>
        <?php endif;?>

        <center><div class="my-container"></div></center>
    </div>
    <div class="clear"></div>
    <?php if (!empty($files)): ?>
        <div class="col-md-6">
            <?php foreach ($files as $file): ?>


                <img class="my-foto" src="<?= Yii::getAlias('@web/images/shop/'). $model->id . '/' . $file->path; ?>"
                     data-large="<?= Yii::getAlias('@web/images/shop/'). $model->id .'/'.$file->path; ?>">

            <?php endforeach; ?>

        </div>

        <div class="col-md-6"></div>
        <div class="clear"></div>
    <?php endif; ?>
    <div class="col-md-12">
<!--        --><?php //if (!Yii::$app->user->isGuest): ?>
            <?= \app\components\ShopCommentWidget::widget(['shopId' => $model->id]); ?>
<!--        --><?php //endif; ?>
    </div>
</div>

<script>
    jQuery(function () {

        //вешаем плагин на контейнер-картинку
        $(".my-foto-container").imagezoomsl({
            descarea: ".my-container",
            zoomrange: [1, 12],
            magnifiereffectanimate: "fadeIn",
            magnifierborder: "none"
        });

        //клик по превью-картинке
        $(".my-foto").click(function () {

            var that = this;

            //копируем атрибуты из превью-картинки в контейнер-картинку
            $(".my-foto-container").fadeOut(600, function () {

                $(this).attr("src", $(that).attr("src"))              // путь до small картинки
                    .attr("data-large", $(that).attr("data-large"))       // путь до big картинки

                    //дополнительные атрибуты, если есть
                    //.attr("data-title",       $(that).attr("data-title"))       // заголовок подсказки
                    //.attr("data-help",        $(that).attr("data-help"))        // текст подсказки
                    //.attr("data-text-bottom", $(that).attr("data-text-bottom")) // текст снизу картинки

                    .fadeIn(1000);
            });
        });
    });
</script>

<style>

</style>
<!--<style>-->
<!--    .my-photo{-->
<!--        border: 1px solid #F0F0F0;-->
<!--        width: 250px;-->
<!--        height: 250px;-->
<!--    }-->
<!--</style>-->

views/shop/_view_dress.php
<?php

use yii\helpers\Html;

$this->registerMetaTag(['name' => 'description', 'content' => 'Проект "Добрые платья" - платье '.$model->number]);
$this->title = 'Проект "Добрые платья" - платье '.$model->number;

?>




<?php $content =' <center>
        <div class="col-md-12">
            <h2>' .$model->number.'</h2>
        </div>
        <img class="shop-image" src="'.  Yii::getAlias('@web/images/shop/'). $model->id . '/small/' . $model->avatar->path  .'">
        <div class="col-md-12" style=" margin-top:20px">
         <h2>Цена : ' .$model->cost.'</h2>
        </div>
    </center>';?>
<!--    <a href="--><?//= \yii\helpers\Url::toRoute(['shop/dress','id'=>$model->id])?><!--">--><?//=$content?><!--</a>-->
<?php echo Html::a($content, [''], ['title' => 'Просмотреть', 'class' => 'deliveryPopup', 'data-dress' => $model->id, 'id' => $model->id]);
?>


<?php \yii\bootstrap\Modal::begin([
    'headerOptions' => ['id' => 'startDelivery'],
    'header' => '<h2>Платье '. $model->number.'</h2>',
    'id' => 'startDelivery',
    'size' => 'modal-lg dress',

]);?>
<div id='modalContent'></div>
<?php \yii\bootstrap\Modal::end(); ?>

views/shop/change.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use vova07\imperavi\Widget;

$this->title = ' Изменить счетчик  : ' . $model->name . ' ' . $model->lastname;

/* @var $this yii\web\View */
/* @var $model app\models\Needies */
/* @var $form yii\widgets\ActiveForm */
?>

<section class="content needies-index">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>

                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>

                    <div class="box-tools">

                    </div>
                </div>
                <div class="box-body">

                    <?php $form = ActiveForm::begin(); ?>


                    <?= $form->field($model, 'name')->textInput(['disabled'=>'disabled']) ?>

                    <?= $form->field($model, 'lastname')->textInput(['disabled'=>'disabled']) ?>

                    <?= $form->field($model, 'need')->textInput() ?>

                    <?= $form->field($model, 'got')->textInput() ?>

                    <div class="form-group">
                        <?= Html::submitButton('Изменить', ['class' => 'btn btn-primary']) ?>

                    </div>

                    <?php ActiveForm::end(); ?>

                </div>
            </div>
        </div>
    </div>
</section>

views/shop/counter.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use dosamigos\datepicker\DatePicker;
use app\models\Statuses;
use yii\helpers\Url;

$this->title = 'Счетчик Кому помочь';
?>

<section class="content needies-index">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>

                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>

                    <div class="box-tools">

                    </div>
                </div>
                <div class="box-body">
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            [
                                'attribute' => 'id',
                                'value' => 'id',
                                'filter' => false
                            ],

                            [
                                'attribute'=>'name',

                                'options' => ['width' => '200'],
                            ],


                            [
                                'attribute'=>'lastname',

                                'options' => ['width' => '200'],
                            ],
                            [
                                'attribute'=> 'need',
                            ],

                            [
                                'attribute'=>'got',
                            ],




                            [
                                'class' => 'yii\grid\ActionColumn',
                                'options' => ['width' => '120'],
                                'template' => '  {update}  ',
                                'urlCreator' => function ($action, $model, $key, $index) {
                                    switch($action){
                                        case 'update':
                                            $url = Url::toRoute(['shop/change','id'=>$model->id]);
                                            return $url;

                                    }
                                }
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</section>

views/shop/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Shop */

$this->title = 'Платье';
$this->params['breadcrumbs'][] = ['label' => 'Shops', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content comments-create">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>

                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
                </div>
                <div class="box-body">
                    <?= $this->render('_form', [
                        'model' => $model,
                        'upload' => $upload,
                        'uploadFile' => $uploadFile,
                    ]) ?>
                </div>
            </div>
        </div>
    </div>
</section>

views/shop/dress.php
<?php

use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

//$this->title = '"Добрые платья" дает возможность за небольшую сумму приобрести красивое платье, пожертвованное во имя спасения чьей-то жизни.';
$this->registerMetaTag(['name' => 'description', 'content' => '"Добрые платья" дает возможность за небольшую сумму приобрести красивое платье, пожертвованное во имя спасения чьей-то жизни.']);
$this->registerMetaTag(['name' => 'keywords', 'content' => Yii::$app->params['keywords']]);
?>

<div class="container b_fixed">
    <div class="b_adds_list">
        <center><h1>Добрые платья</h1></center>
        <div style="display:inline-block; float: left;margin-bottom: 20px;width: 20%;margin-right: 20px"><a href="<?= Url::toRoute(['needies/more','id'=>106])?>"><h3>AЛЕКСА ДАРИЯ</h3><img style="width:100%;" class="sp-image" src="<?= Yii::getAlias('@web/images/484/m_6deb154a84a0da007633ee1389e971f5.jpg')?>"></a></div>
        <div style="margin-bottom: 20px; margin-top: 60px "><p>Проект "Добрые платья" дает возможность за небольшую сумму приобрести красивое платье, пожертвованное во имя спасения чьей-то жизни. Приобретая себе обновку, Вы фактически покупаете жизненно-необходимые препараты для больного человека или помогаете в проведении операции. Мы все знаем, что кроме мира, который мы видим, есть и другой тонкий мир, где все наши материальные блага ровным счётом ничего не стоят. То душевное богатство, которое мы накапливаем, имеет гараздо большее значение.

                У каждой женщины в шкафу есть платье, которое пылится там уже долгое время.
                Это платье может спасти чью—то жизнь! Присоединяйтесь к нашему проекту, дарите и приобретайте платья—дарите надежду людям, оказавшимся в тяжелой ситуации.
                Мы подаем руку помощи сейчас, а Вселенная обязательно отблагодарит нас позже!
                Оттдавая, мы всегда получаем вдвое больше.</p>
        <br>
        <p>
            Если Вам понравилось платье и Вы хотите его приобрести или примерять - обращайтесь по телефону <b>+380730763097 - Дария.</b> Оплата за платье только на карту приват банка. Таким образом, мы каждый раз будем готовы ответить на вопрос: сколько же собрано Дарии на лекарства?
           <br><b> Номер карты 4149 4978 5139 2763 - Приват Банк Алекса Дария</b>
        </p></div>

        <?php if (!empty($needies->need) && !empty($needies->got)): ?>
            <div class="b_progress_amount">
                <label><b>Собрано:</b> <?= $needies->got . ' грн' ?> из <?= $needies->need . ' грн' ?> </label>
                <?php $percent = $needies->got / $needies->need * 100 ?>
                <div class="b_progress_place">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="10" aria-valuemin="0"
                             aria-valuemax="<?= $needies->need ?>" style="width: <?= $percent; ?>%;">

                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div style="margin-bottom: 100px;"></div>
        <?= \yii\widgets\ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_view_dress',
            'layout' => "{summary}\n{items}<div class=\"clr\"></div>{pager}",
            'emptyText' => 'На данный момент наш магазин пуст',
            'itemOptions' => [
                'tag' => 'div',
                'class' => 'col-md-3 shop',
            ],
        ]) ?>

    </div>

</div>

views/shop/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ShopViewSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Магазин';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content comments-index">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-star"></i>

                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>

                    <div class="box-tools">
                        <?= Html::a('Создать лот', ['create'], ['class' => 'btn btn-success']) ?>
                    </div>
                </div>
                <div class="box-body">


                    <?= \yii\grid\GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            'number',
                            'size',
                            'color',
                            'consist',
                            'cost',
                            'avatarId',

                            [
                                'class' => 'yii\grid\ActionColumn',
                                'options' => ['width' => '120'],
                                'template' => '{message} {comment} {view} {update}  {delete}',
                                'buttons' => [
                                    'message' => function ($url, $model) {
                                        return Html::a('<span class="glyphicon glyphicon-shopping-cart"></span>', $url, [
                                            'title' => Yii::t('app', 'Сообщение'),
                                        ]);
                                    },



                                ],
                                'urlCreator' => function ($action, $model, $key, $index) {
                                    switch ($action) {
                                        case 'message':
                                            $url = Url::toRoute(['shop/watermark','id'=>$model->avatarId]);
                                            return $url;
                                        case 'view':
                                            $url = Url::toRoute(['shop/view','id'=>$model->id]);
                                            return $url;
                                        case 'update':
                                            $url = Url::toRoute(['shop/update','id'=>$model->id]);
                                            return $url;
                                        case 'delete':
                                            $url = Url::toRoute(['shop/delete','id'=>  $model->id]);
                                            return $url;
                                    }


                                }
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</section>

views/shop/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Shop */

$this->title = 'Изменить лот: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Shops', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<section class="content static-pages-update">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>

                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
                </div>
                <div class="box-body">

                    <?= $this->render('_form', [
                        'model' => $model,
                        'upload' => $upload,
                        'uploadFile' => $uploadFile,
                    ]) ?>

                </div>
            </div>
        </div>
    </div>
</section>

views/shop/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Shop */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Shops', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content comments-view">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>

                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>

                    <div class="box-tools">
                        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]) ?>
                    </div>
                </div>
                <div class="box-body">

                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'number',
                            'size',
                            'color',
                            'consist',
                            'cost',
                            'avatarId:image',
                        ],
                    ]) ?>

                </div>
            </div>
        </div>
    </div>
</section>