models/Volunteers.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "volunteers".
 *
 * @property integer $id
 * @property integer $userId
 * @property string $name
 * @property string $lastname
 * @property integer $age
 * @property integer $cityId
 * @property string $phone
 * @property string $email
 * @property string $vk
 * @property string $fb
 * @property integer $avatarId
 * @property integer $statusId
 *
 * @property VolunteerHelp[] $volunteerHelps
 * @property VolunteerTask[] $volunteerTasks
 * @property Users $user
 * @property Cities $city
 * @property Statuses $status
 */
class Volunteers extends \yii\db\ActiveRecord
{
    public $type = 3;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'volunteers';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['userId', 'name', 'lastname', 'age','mainCountryId', 'city', 'phone', 'email', 'showPhone', 'showEmail', 'help'], 'required'],
            [['userId', 'cityId', 'mainCountryId', 'showPhone', 'avatarId', 'statusId'], 'integer'],
            [['email'], 'email'],
            [['age'], 'integer', 'max' => 99],
            [['city', 'phone', 'email', 'vk', 'fb','time'], 'string', 'max' => 120],
            [['name','lastname'],'string','max'=>20],
            [['createTime'],'string','max'=>255],
            [['help'], 'string'],
            [['type'],'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userId' => 'ID Пользователя',
            'name' => 'Имя',
            'lastname' => 'Фамилия',
            'age' => 'Возраст',
            'city' => 'Город',
            'cityId' => 'Город',
            'phone' => 'Телефон',
            'email' => 'Email',
            'vk' => 'Ссылка на страницу в VK',
            'fb' => 'Ссылка на страницу в FB',
            'showPhone' => 'Показывать телефон',
            'showEmail' => 'Показывать  email',
            'help' => 'Могу помочь',
            'avatarId' => 'Aватар',
            'statusId' => 'Статус',
            'time' => 'Укажите удобное время для звонка',
            'mainCountryId'=>'Страна',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVolunteerHelps()
    {
        return $this->hasMany(VolunteerHelp::className(), ['volunteerId' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVolunteerTasks()
    {
        return $this->hasMany(UserTask::className(), ['volunteerId' => 'id']);
    }

    /**
     *
     */
    public function getAvatar()
    {
        return $this->hasOne(Files::className(), ['id' => 'avatarId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'userId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCities()
    {
        return $this->hasOne(Cities::className(), ['id' => 'cityId']);
    }

    public function getCityTitle()
    {
        return $this->cities->title;
    }

    public function getCountry()
    {
        return $this->hasOne(Countries::className(), ['mainId' => 'mainCountryId']);
    }

    public function getCountryTitle()
    {
        return $this->country->title;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Statuses::className(), ['id' => 'statusId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFile()
    {
        return $this->hasOne(Files::className(), ['id' => 'avatarId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRating()
    {
        return $this->hasOne(Ratings::className(), ['userId' => 'userId']);
    }

    /**
     * @return mixed
     */
        public function getRatingCount() {
        return $this->hasMany(Ratings::className(), ['userId' => 'userId'])
            ->sum('rating');
    }

    /** @inheritdoc */
    public function beforeSave($insert)
    {
        $this->setAttribute('vk', Yii::$app->DLL->getLinkId($this->vk));
        $this->setAttribute('fb', Yii::$app->DLL->getLinkId($this->fb));
        return parent::beforeSave($insert);
    }

    /** @inheritdoc */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        if ($insert) {
            $role = key(Yii::$app->authManager->getRolesByUser($this->userId));
            if (empty($role)) {
                $auth = Yii::$app->authManager;
                $authorRole = $auth->getRole('volunteer');
                $auth->assign($authorRole, $this->userId);
            }
        }
    }

    /**
     * @return array|\yii\db\ActiveRecord[]
     */
    public function getNewVolunteers()
    {
        $time = time()-86400;
        return $this->find()
            ->where('createTime >' . $time)
            ->asArray()
            ->all();
    }

    /**
     * @return array|\yii\db\ActiveRecord[]
     */
    public function getReversedVolunteers()
    {
        return $this->find()
            ->where(['statusId' => 4])
            ->asArray()
            ->all();
    }
}

controllers/VolunteersController.php
<?php

namespace app\controllers;

use app\models\Cities;
use app\models\Comments;
use app\models\Countries;
use app\models\Files;
use app\models\Statuses;
use app\models\UploadForm;
use app\models\Users;
use Yii;
use app\models\Volunteers;
use app\models\VolunteersSeach;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\data\Pagination;
use yii\imagine\Image;
use yii\web\UploadedFile;

/**
 * VolunteersController implements the CRUD actions for Volunteers model.
 */
class VolunteersController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }


    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {

            if(!Yii::$app->user->isGuest) {
                Yii::$app->DLL->onliner(Yii::$app->user->id);
            }

            $role = key(Yii::$app->authManager->getRolesByUser(Yii::$app->user->id));
            if ($action->id != 'list' && $action->id != 'more') {
                if (!Yii::$app->user->can('adminIndex')) {
                    Yii::$app->session->setFlash('error', 'Доступ запрещен');
                    return $this->redirect('/site/index', []);
                } else {
                    $this->layout = 'admin';
                }
            } elseif ($role == 'admin') {
                return $this->redirect(['subscribe/index']);
            }
            return true;
        }
        return false;
    }

    /**
     * Lists all Volunteers models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VolunteersSeach();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Volunteers model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $filesModel = new Files();
        $model = $this->findModel($id);
        $images = $filesModel->getFileType($model->userId, 1);
        return $this->render('view', [
            'model' => $model,
            'images' => $images,
        ]);
    }

    /**
     * Creates a new Volunteers model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Volunteers();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'cities' => ArrayHelper::map(Cities::find()->asArray()->all(), 'id', 'title'),
                'statuses' => ArrayHelper::map(Statuses::find()->all(), 'id', 'title')
            ]);
        }
    }

    /**
     * Updates an existing Volunteers model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $filesModel = new Files();
        $model = $this->findModel($id);
        $images = $filesModel->getFileType($model->userId, 1);
        $upload = new UploadForm();
        $upload->scenario = 'avatarUpload';

        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            if (!empty($upload->imageFile)) {
                $model->avatarId = $upload->upload($model->userId);
            }
            $model->fb = Yii::$app->DLL->getLinkId($model->fb);
            $model->vk = Yii::$app->DLL->getLinkId($model->vk);
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'upload' => $upload,
                'countries' => ArrayHelper::map(Countries::find()->orderBy(['order' => SORT_ASC])->all(), 'mainId', 'title'),
                'cities' => ArrayHelper::map(Cities::find()->where(['countryId' => 2])->orderBy(['title' => SORT_ASC])->asArray()->all(), 'id', 'title'),
                'statuses' => ArrayHelper::map(Statuses::find()->all(), 'id', 'title'),
                'images' => $images,
            ]);
        }
    }

    /**
     * Deletes an existing Volunteers model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = new Users();
        $userArr = $this->findModel($id);
        $user = $model->findOne(['id'=>$userArr->userId]);
        $user->delete();
        return $this->redirect(['index']);
    }


    /**
     * @return string
     */
    public function actionList()
    {

        $volunteer = new ActiveDataProvider([
            'query' => Volunteers::find()->where(['statusId' => 2])->orderBy(['rating' => SORT_DESC, 'id' => SORT_DESC]),
            'pagination' => [
                'pageSize' => 8,
            ],
        ]);
        return $this->render('list', [
            'volunteer' =>$volunteer
        ]);
    }


    /**
     * @return string
     */
    public function actionMore($id)
    {
        return $this->render('more', [
            'model' => $this->findModel($id)
        ]);
    }

    /**
     * Finds the Volunteers model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Volunteers the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Volunteers::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionDelavatar()
    {
            $filesModel = new Files();
            $avatarId =Yii::$app->request->post('avatarId');
            $delete = $filesModel->findOne(['id' => $avatarId]);
            $delete->delete();
    }

    public function actionApproved($id)
    {
        $volunteerModel = new Volunteers();
        $volunteer = $volunteerModel->findOne(['id'=>$id]);
        $volunteer->statusId = 2;
        $volunteer->save(false);
        return $this->redirect(['index']);
    }

    public function actionRotateImg()
    {
        $id = Yii::$app->request->post('id');
        $side = Yii::$app->request->post('side');
        if ($id !== null || $side !== null) {
            $imagine = Image::getImagine();
            $file = Files::findOne($id);
            $path = realpath(Yii::getAlias('@app') . '/web/images/' . $file->userId . '/' . $file->path);
            $pathM = realpath(Yii::getAlias('@app') . '/web/images/' . $file->userId . '/m_' . $file->path);
            $image = $imagine->open($path);
            $imageM = $imagine->open($pathM);
            $angle = null;
            if ($side == 'left') {
                $angle = -90;
            } else {
                $angle = 90;
            }
            $image->rotate($angle)->save($path);
            $imageM->rotate($angle)->save($pathM);
        }
    }

    public function actionComment($id)
    {
        $user = new Volunteers();
        $model = new Comments();
        $statusModel = new Statuses();
        $status = $statusModel->getAllStatuses();
        $volunteer = $user->find()->where(['id'=>$id])->one();

        if ($model->load(Yii::$app->request->post())) {

            $model->save();

            return $this->redirect(['index']);
        }
        return $this->render('comment',[
            'model'=>$model,
            'volunteer'=>$volunteer,
            'status'=>$status,
        ]);
    }
}

views/volunteers/_info.php
<h3><?= $model->name . ' ' . $model->lastname ?></h3>
<span class="city"><?= $model->countryTitle . ', ' . $model->city ?></span> <br>
<p>

</p>

<p><b>Возраст: </b> <?= $model->age ?> <?= Yii::$app->DLL->getWordEnd('', 'лет', 'год', 'года', 'лет', $model->age) ?></p>

<?php if(!empty($model->phone) && $model->showPhone == 0): ?>
    <p><b>Телефон: </b><?= $model->phone ?></p>
<?php endif ?>

<?php if(!empty($model->email) && $model->showEmail == 0): ?>
    <p><b>Email: </b><?= $model->email ?></p>
<?php endif ?>

<?php if(!empty($model->help)): ?>
    <p><b>Могу помочь: </b><?= $model->help ?></p>
<?php endif ?>

<?php if(!empty($model->vk)): ?>
    <a target="_blank" href="https://www.vk.com/<?= $model->vk ?>"><i class="fa social fa-vk"></i></a>
<?php endif ?>

<?php if(!empty($model->fb)): ?>
    <a target="_blank" href="https://facebook.com/<?= $model->fb ?>"><i class="fa social fa-facebook-official"></i></a>
<?php endif ?>

views/volunteers/_view_list.php
<?php

use yii\helpers\Url;
?>

<div class="col-md-6 col-sm-6 col-xs-12 b_persons">
    <div class="b_persons_item">
        <div class="b_pic"><a href="<?= Url::toRoute(['more', 'id' => $model->id]) ?>">
                <?php if(!empty($model->file->path) && file_exists(Yii::getAlias('@app/web/images/' . $model->userId . '/m_' . $model->file->path))): ?>
                    <img src="<?= Yii::getAlias('@web') . '/images/' . $model->userId . '/m_' . $model->file->path ?>" style="width: 106px" ></a></div>
                <?php else: ?>
                    <img src="<?= Yii::getAlias('@web') . '/images/no-image-man.png' ?>" style="width: 106px"></a></div>
                <?php endif; ?>
<!--                <img src="gfx/pic1.jpg"></a></div>-->
        <div class="b_desc_content" style="height: 116px;">
            <div class="b_title"><a href="<?= Url::toRoute(['more', 'id' => $model->id]) ?>"><?= $model->name . ' ' . $model->lastname ?></a><span class="b_locate"><?= $model->age . ' ' . Yii::$app->DLL->getWordEnd('', 'лет', 'год', 'года', 'лет', $model->age) . ' ' . $model->countryTitle . ', ' . $model->city ?></span>
            </div>
            <div class="b_desc"><span class="b_rating"><?= !empty($model->rating) ? 'Рейтинг: ' . $model->rating : ' ' ?></span></div>
        </div>
    </div>
</div>

views/volunteers/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use app\models\Statuses;

$this->title = 'Волонтеры';
?>

<section class="content volunteers-index">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>

                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>

                    <div class="box-tools">
                        <? //= Html::a('Create Volunteer', ['create'], ['class' => 'btn btn-success']) ?><!--</p>-->
                    </div>
                </div>
                <div class="box-body">
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            [
                                'attribute' => 'id',
                                'value' => 'id',
                                'filter' => false
                            ],
//                            'userId',
                            'name',
                            'lastname',
                            'age',
                            [
                                'attribute'=>'mainCountryId',
                                'value'=>'countryTitle',
                                'filter'=>ArrayHelper::map(\app\models\Countries::find()->orderBy(['order' => SORT_ASC])->all(), 'mainId', 'title'),
                            ],
                            [
                                'attribute'=>'city',
                                'value'=>'city',
                            ],
                            'email:email',
                            'phone',
                            [
                                'attribute' => 'statusPosition',
                                'label' => 'Статус',
                                'format' => 'raw',
                                'value' => function ($data) {
                                    $status = $data->status->title;
                                    switch ($status) {
                                        case 'новый':
                                            return '<span class="label bg-green "> ' . $data->status->title . '</span>';
                                            break;
                                        case 'измененный':
                                            return '<span class="label bg-blue "> ' . $data->status->title . '</span>';
                                            break;
                                        case 'отклоненный':
                                            return '<span class="label bg-yellow "> ' . $data->status->title . '</span>';
                                            break;
                                        default:
                                            return $data->status->title;
                                            break;
                                    }
                                },
                                'filter' => ArrayHelper::map(Statuses::find()->select(['id', 'title'])->all(), 'id', 'title'),
                            ],

                            [
                                'attribute' => 'createTime',
                                'format' => 'raw',
                                'label' => 'Пользователь',
                                'filter' => false,
                                'value' => function($data)
                                {
                                    $time = time()-86400;
                                    if($data->createTime > $time){
                                        return '<span class="label bg-green "> ' . новый . '</span>';
                                    }else{
                                        return 'просмотреный';
                                    }
                                }
                            ],


                            [
                                'class' => 'yii\grid\ActionColumn',
                                'options' => ['width' => '120'],
                                'template' => '{message} {comment} {view} {update}  {delete}',
                                'buttons' => [
                                    'message' => function ($url, $model) {
                                        return Html::a('<span class="glyphicon glyphicon-envelope"></span>', $url, [
                                            'title' => Yii::t('app', 'Сообщение'),
                                        ]);
                                    },
                                    'comment' => function ($url, $model) {
                                        return Html::a('<span class="glyphicon glyphicon-comment"></span>', $url, [
                                            'title' => Yii::t('app', 'Комментарий'),
                                        ]);
                                    },
                                ],
                                'urlCreator' => function ($action, $model, $key, $index) {
                                    switch ($action) {
                                        case 'message':
                                            $url = Url::toRoute(['admin/messages','type'=>3,'id'=>$model->userId]);
                                            return $url;
                                        case 'view':
                                            $url = Url::toRoute(['volunteers/view','id'=>$model->id]);
                                            return $url;
                                        case 'update':
                                            $url = Url::toRoute(['volunteers/update','id'=>$model->id]);
                                            return $url;
                                        case 'delete':
                                            $url = Url::toRoute(['volunteers/delete','id'=>$model->id]);
                                            return $url;
                                        case 'comment':
                                            $url = Url::toRoute(['volunteers/comment','id'=>$model->id]);
                                            return $url;

                                    }
                                }
                            ],],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</section>

views/volunteers/more.php
<?php

use app\components\WallWidget;
use app\components\RatingPopupWidget;
use app\components\HelpToHistoryWidget;

$this->title =  $model->name . ' ' . $model->lastname .' - волонтер благотворительной организации Мир добрых людей';
$this->registerMetaTag(['name' => 'description', 'content' =>'Волонтер '.$model->name . ' ' . $model->lastname .' принимает активное участие в помощи детям и взрослым и вносит весомый вклад в наш проект']);
$this->registerMetaTag(['name' => 'keywords', 'content' => Yii::$app->params['keywords']]);
?>


    <div class="container b_fixed">
        <div class="b_left-side b_left_side_qustionare col-md-4 col-sm-4 col-xs-12">
            <div class="b_left_slider_person">
                <div class="slider-pro" id="b_person-slider">
                    <div class="sp-slides">
                        <!-- Slide 1 -->
                        <div class="sp-slide">
                            <?php if (!empty($model->file->path) && file_exists(Yii::getAlias('@app/web/images/' . $model->userId . '/' . $model->file->path))): ?>
                                <img style="width:280px;" class="sp-image"
                                     src="<?= Yii::getAlias('@web') . '/images/' . $model->userId . '/m_' . $model->file->path ?>"/>

                            <?php else: ?>
                                <img style="width:280px;" class="sp-image"
                                     src="<?= Yii::getAlias('@web') . '/images/noavatar.png' ?>"/>

                            <?php endif; ?>

                        </div>

                    </div>
                </div>

            </div>
            <center>
                <button type="button"
                        style="color: #fff; background: #006cff;border-radius: 20px;border-color: #006cff;box-shadow: none;"
                        class="btn btn-success" data-toggle="modal" data-target="#ratingModal">
                    Рейтинг <?= $model->ratingCount ?></button>
            </center>

        </div>
        <div class="b_person_desc col-md-8 col-sm-8 col-xs-12 pull-right">
            <div class="b_name"><h1><?= $model->name . ' ' . $model->lastname ?></h1><span
                    class="b_locate"><?= $model->age ?> <?= Yii::$app->DLL->getWordEnd('', 'лет', 'год', 'года', 'лет', $model->age) . ' ' . $model->countryTitle . ', ' . $model->city ?></span>
            </div>
            <p><b>Возраст:</b>
                <?= $model->age ?> <?= Yii::$app->DLL->getWordEnd('', 'лет', 'год', 'года', 'лет', $model->age) ?></p>
            <?php if (!empty($model->email) && $model->showEmail == 0): ?>
                <p><b>Email :</b> <?= $model->email ?></p>
            <?php endif ?>

            <?php if (!empty($model->phone) && $model->showPhone == 0): ?>
                <p><b>Телефон: </b><?= $model->phone ?></p>
            <?php endif ?>
            <?php if (!empty($model->help)): ?>
                <p><b>Могу помочь: </b><?= $model->help ?></p>
            <?php endif ?>
            <?php if (!empty($model->vk)): ?>
                <a target="_blank" href="https://www.vk.com/<?= $model->vk ?>"><i class="fa social fa-vk"></i></a>
            <?php endif; ?>
            <?php if (!empty($model->fb)): ?>
                <a target="_blank" href="https://facebook.com/<?= $model->fb ?>"><i
                        class="fa social fa-facebook-official"></i></a>
            <?php endif; ?>
            <?= WallWidget::widget(['userId' => $model->userId]); ?>
        </div>


    </div>

<?= RatingPopupWidget::widget(['userId' => $model->userId]); ?>

views/volunteers/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

$this->title = 'Волонтер : ' . $model->name . ' ' . $model->lastname;
?>

<section class="content volunteers-view">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
                    <div class="box-tools">
                        <?php if($model->statusId != 2):?>
                            <?= Html::a('Подтвердить', ['approved', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
                        <?php endif;?>
                        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]) ?>
                    </div>
                </div>
                <div class="box-body">

                    <table class="table table-striped table-bordered detail-view">

                        <tbody>
                        <tr>
                            <th>Имя</th>
                            <td><?= $model->name ?></td>
                        </tr>

                        <tr>
                            <th>Фамилия</th>
                            <td><?= $model->lastname ?></td>
                        </tr>

                        <tr>
                            <th>Возраст</th>
                            <td><?= $model->age ?></td>
                        </tr>

                        <tr>
                            <th>Страна</th>
                            <td><?= $model->countryTitle ?></td>
                        </tr>
                        <tr>
                            <th>Город</th>
                            <td><?= $model->city ?></td>
                        </tr>


                        <tr>
                            <th>Телефон</th>
                            <td><?= $model->phone ?></td>
                        </tr>
                        <tr>
                            <th>Удобное время для звонка</th>
                            <td><?= $model->time ?></td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td><?= $model->email ?></td>
                        </tr>

                        <tr>
                            <th>Ссылка на страницу в FB</th>
                            <td>
                                <?php if(!empty($model->fb)) :?>
                                <a target="_blank" href="https://facebook.com/<?= $model->fb ?>"><?= 'facebook.com/' . $model->fb ?></a>
                                <?php endif;?>
                            </td>
                        </tr>

                        <tr>
                            <th>Ссылка на страницу в VK</th>
                            <td>
                                <?php if(!empty($model->vk)) :?>
                                <a target="_blank" href="https://www.vk.com/<?= $model->vk ?>"><?= 'www.vk.com/' . $model->vk ?></a>
                                <?php endif;?>
                            </td>
                        </tr>

                        <tr>
                            <th>Могу помочь</th>
                            <td><?= $model->help ?></td>
                        </tr>

                        <tr>
                            <th>Аватарка</th>
                            <td> <?php $file = $model->file->path; ?>
                                <?php if (!empty($file)): ?>
                                    <a href="<?= Yii::getAlias('@web') . '/images/' . $model->userId . '/m_' . $file ?>"><img src="<?= Yii::getAlias('@web') . '/images/' . $model->userId . '/m_' . $file ?>"></a>
                                <?php else: ?>
                                    <div class="image-user">
                                        <img src="<?= Yii::getAlias('@web') . '/images/no-image.jpeg'?>">
                                    </div>
                                <?php endif; ?>
                            </td>
                        </tr>

                        <tr>
                            <th>Статус</th>
                            <td><?= $model->status->title ?></td>
                        </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</section>